MODULE M_FILES_VARS
  IMPLICIT NONE
  PRIVATE

  CHARACTER(LEN=80),PUBLIC:: cTitle
  
  ! Input File Name
  CHARACTER(LEN=80),PUBLIC:: NamFInn
  CHARACTER(LEN=80),PUBLIC:: NamFLogK,NamFEle,NamFKin,NamFSol,NamFPtz
  CHARACTER(LEN=80),PUBLIC:: NamDtbAqu,NamDtbMin,NamDtbMlt

  CHARACTER(LEN=80),PUBLIC:: DirOut,DirLog
  CHARACTER(LEN=80),PUBLIC:: DirDtbOut,DirDtbLog 

END MODULE M_FILES_VARS
